repos:
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
  - id: clippy
    args:
      - "--fix"
      - "--allow-dirty"
  - id: cargo-check

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.22.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
- repo: local
  hooks:
    - id: cargo-test-docs
      language: system
      types: [rust]
      name: cargo test --doc
      entry: cargo test --doc
      pass_filenames: false