[package]
name = "fxr-binary-reader"
version = "0.1.0"
edition = "2024"

[lib]
name = "fxr_binary_reader"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
insta = "1.42.2"
memmap2 = "*"
thiserror = "2"
zerocopy-derive = "*"
zerocopy = "*"